name: authentication_repository
description: Dart package to manage authentication
publish_to: none

environment:
  sdk: ">=2.15.0-178.1.beta <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.0

dependencies:
  http: ^0.13.4
